version:
  name: velociraptor
  version: 0.6.6
Client:
  server_urls:
  - https://10.100.30.4:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDIDCCAgigAwIBAgIRAMRKY756DWN67NXaEARwo5AwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMDgyNjIxMjUxOVoXDTIz
    MDgyNjIxMjUxOVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApJ2ffxkK3RjoSlcHc/fuE4YSsr2hPTMy
    jd7CyFOXrXpBUAmgjfcT1fz8ne0NNv6fXm6Czz97x17Hwe7869uq9dZpJu+jhL38
    I0eopIIBmqFuTaZhT8oXdhn8wX869Y2YegnTDCnnMl/qU/mG6NzeCFVxxyLfIvqr
    O+Xb9YioMY0khT9RVJoHPKlJpaEjrtct0OOzqtruX/7Iocu380QAYYl+UyfQzLmG
    mv1dGjGeHS9db/zNyhQIIfgC5Lt3yjjlxgtn2PGA0AuepTYBUsBXJcS/sIZNJuTT
    UUUhDULN5olcThF5WtsXOOrnGmDV8VYokn+yieZdBW4cBlucVxeB4QIDAQABo2Ew
    XzAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFJLb+hleEb6A2oJEuv6Xnni26Nwc
    MA0GCSqGSIb3DQEBCwUAA4IBAQATf8qTqWkZJa4Fpc4qqnpjmrGP0vTFk0Xn3ll+
    PM28/k4dgibPL/JaTr3851N4DIYIWfADcIt1hHvKNZN5VqbhvC7dTRSHGgvZmmLL
    iyd9usC4C0jF8YAkHAQn8XGqKMXLn1074BN//XmxIHjmSINxcUzLSlXKOXqTV/Tw
    oQwOtdCNtYB51Hd80AvVlNgRklVVV6pTTvQVClxs/XwCbcgpotPPV6Z7IpXyA2QW
    5vAzu201kK74JGDGTXO/9lTaSAFvkfax0kHh3ylsMVuidFbe2IQH5CNN+EK6jJD3
    y3m2/uzi9BOI31oA1db9VLuQehq2LmiOzxEdLZAgX/3h1VrZ
    -----END CERTIFICATE-----
    
  nonce: dStW1TofRz8=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.6
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  bind_address: 10.100.30.4 
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: 10.100.30.4 
  bind_port: 8889
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQjCCAiqgAwIBAgIRAPJs1BPwxIAFDy16FjZXc9owDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMDgyNjIxMjUxOVoXDTIz
    MDgyNjIxMjUxOVowKTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRAwDgYDVQQDDAdH
    UlBDX0dXMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApqXvAFVzxv7A
    gTCq9GF1wN7lnxp2evIAvFANnPx5tS9L7y1BQifHUSZrgnT4x5KYaoA06CkDJQgT
    6Y0g1ZiDrOvqY70EbSUazbtHoVSJEoJZohipmLzfuWeKiXKdbMR3jpxJlOdTtX6A
    IPIyai+z40/49QVNIVVKrSdUWEYH9W7K0V7FeTsmB+yp1aMh7dD+++F4dCWuZLz1
    q1KxFufJbdr6/SGpu4FXwHMxfR5g+8dvtybM4RU5JXCzNQFvU0+48hLhX1ZIOz/t
    z7zTMW7aS0yoMTH5yl6O4M4JTqpG3e3AFDr60jNoueV5y3ofhfqcSxQTPsUp5dTS
    5aZjuvLw5wIDAQABo3QwcjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUktv6GV4R
    voDagkS6/peeeLbo3BwwEgYDVR0RBAswCYIHR1JQQ19HVzANBgkqhkiG9w0BAQsF
    AAOCAQEAW9VcPrhAXNkplYraF6esSjjOoC9VfO4YQ0w2zWTzcvHKavWHv+wTJEmo
    2/E9YKlwigwNgcC7xjHZCkkRpZfVTuJqdxYHhRE3m5grec65N7ukhcsv+HA0JMyT
    PkFJBzjsvSIYiyvyuRY9lCQDB5rtypKCO5CGQoUWNbeUeJfjU0mbFb+itOm+p9US
    lXzSYsbzBW1OH/d2ncjswzdg79KCfBteLuobfrmoHjw+wHw4nYD6sVhElTNo4KL3
    JMZa3hOjmmBEbQ/kfuQoRG2O6rY0pkC+HrztDdv/4ZQm0ZdRPJ9wx0r7Vd6KStfo
    4SiavsPPhSkPhjPLfX5QoklS+z/5Xw==
    -----END CERTIFICATE-----
    
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEApqXvAFVzxv7AgTCq9GF1wN7lnxp2evIAvFANnPx5tS9L7y1B
    QifHUSZrgnT4x5KYaoA06CkDJQgT6Y0g1ZiDrOvqY70EbSUazbtHoVSJEoJZohip
    mLzfuWeKiXKdbMR3jpxJlOdTtX6AIPIyai+z40/49QVNIVVKrSdUWEYH9W7K0V7F
    eTsmB+yp1aMh7dD+++F4dCWuZLz1q1KxFufJbdr6/SGpu4FXwHMxfR5g+8dvtybM
    4RU5JXCzNQFvU0+48hLhX1ZIOz/tz7zTMW7aS0yoMTH5yl6O4M4JTqpG3e3AFDr6
    0jNoueV5y3ofhfqcSxQTPsUp5dTS5aZjuvLw5wIDAQABAoIBACcTS3pRjyc+/taM
    GdnZrGnAGil3ZAaqDiAZyUdhMAya/XwkqWOgviy6DIV3dgodxp1aWI2DaFhbj4e4
    7tUGwQFgBALFBG+vPpy06DPdBZMQe4H1tHa6+t6Xd7WI6X7ihoIrBVnj8A3jjpmr
    EMUzUEPhsaeKSa6iODNnwHA+Y4lZwzrrGdzjNXB4SDkl1wX06Vm3itcdMHyLONe+
    uvwK2cptJykA39R7bNN3NerROpYH2p4jY/vU2nSs4FmIlhfuyTCulSFJr1QVVtRU
    nrNMg2RsMU60uUzcWc8HB2vnkr6A+x39+i5zIw9YeQJtsT8J1TcpaXCWsBaztK6W
    U2ESOUECgYEAxHyt2NGHgHysXDWyETqLaT6esoOb8ubXhfkimQPwAwd3iHlIOFlu
    egRRzmE/WIZND24qDTzcEo3OQ8PCJCAb/1dvxbUDnyvPPyEK0E0Q/pEJSPNvKTXB
    ls2kbe8I4Z5HceHrzwrUjDwQKmx5QWA4haVPpVBEE/hMjFQOOI7a0iECgYEA2R+X
    1upJcIpF31nn5l96Tkcu33vS9KdMhCdogZRtpAcVNN+0+p1XqbohdsynpsyQeM6x
    YYOXQMnKGaQs0zZz3EOH1x2KRlet8HD3S75Y2VzyKd4FUVQqPlYmwDDzqfMKBC5C
    cMpMGD1WS5uY7+1dqdBapqOenGS2+zcAklXU8gcCgYEAhzb1u/uVMAqb4mjhPZH4
    VljNhTOkoifRsVSdRoe7J5p/2976oCyLJlTKpyetHBJv/Wpmbe2v1OTZSTDx7UJb
    ggB93qSO9X6EhIEMnAQs6cKNjTJZERb5PfoOacjRZ9IwgGJkkHp3gnni9g7n8uFw
    hCgbAzyVXNjGdNtzXeCRHYECgYEAiK5Cv6AtKxNgeQH34iYosC5Pa5BfdHP8zxSf
    zTLK8n8i8m4BV+LE1Ku/dTHQOEh+ig5Ty7cy+C4Pc6TOMwgMV5SLZvfJnA6GCN6U
    TrI87Fh+eayyXEhHb4Z8TnCCc3Hz1D3qxWYUEQ5LzLzewesDE2t+JXjK2Fjud6Zg
    Tb6KlvECgYEAqKfCDK6BiBYG9ztJ9c5Qktf3RtIvzrLdZLiCFWezamkojDyyHOsl
    /bR5cCJ0IQsdmUNFHYXK3QpeCRSSFt4Ju/tooIyown7mHoMcPybDG8NIt0kg1s9t
    FXBD35NjGsnj22NU/9OkcJCB9BjYk8AJp6B5b+b7gM5z3wxp2mjopjQ=
    -----END RSA PRIVATE KEY-----
    
  internal_cidr:
  - 127.0.0.1/12
  - 192.168.0.0/16
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEApJ2ffxkK3RjoSlcHc/fuE4YSsr2hPTMyjd7CyFOXrXpBUAmg
    jfcT1fz8ne0NNv6fXm6Czz97x17Hwe7869uq9dZpJu+jhL38I0eopIIBmqFuTaZh
    T8oXdhn8wX869Y2YegnTDCnnMl/qU/mG6NzeCFVxxyLfIvqrO+Xb9YioMY0khT9R
    VJoHPKlJpaEjrtct0OOzqtruX/7Iocu380QAYYl+UyfQzLmGmv1dGjGeHS9db/zN
    yhQIIfgC5Lt3yjjlxgtn2PGA0AuepTYBUsBXJcS/sIZNJuTTUUUhDULN5olcThF5
    WtsXOOrnGmDV8VYokn+yieZdBW4cBlucVxeB4QIDAQABAoIBAQCP/m0ZMV+mXXY8
    KPqU/6faninW/jd/oDw1i0kZEL4Z+loNWA6AgENyqLSUtFod5AamBMcZ4K82i3ry
    8kl9Sw61spMSgwanQ8S9W55yIGKkz1b8R3DR6bYyEbNd0xxQ1UYuYk+hUToyf2Ir
    iJbxNNpnsc4v4hoLr/d/EqcglSSDCkr5gB5402Til2svE5N7NRBsLtaRJDZw8Tqc
    hYdY8HKHaF4VlbWIsP5HfUfdBIT166zWnrsTFexRCSD5WTgSn32T3qEGjTmVmI19
    +9igHwcGldnFgdc2slQJ8D4htLdUTH68659tiu/MSeP3Po6GlS/HUmeaQ/HnnClm
    Prcml3/RAoGBAMOEB2NFIVMLVNLBEOqz8RDCaC+6OYwz5i2iyFTK+Kn4HfNCUKMv
    PMrbf0IkrMQii9hHo6HygSuoWOG1rzR/ebP+QUY5fs6VDhkgkAIdAHvXScfCYajz
    wENUC74J6Khm367zVnZUVSjcWIx7l4beQD/rWmoRlUp3IWVOEqQu+r/9AoGBANeK
    c2F2AcgRtkoAlzIDwrvv+ObicthCmGd9rNcGRGsQ3hV7ZlvGPzlmMPlGDM/AN4Cp
    9KSPzWq+wHBFpcHjZGvOETqRIndqKPHbHVC2QgGWZkg8+MgMG0QoTp7UhZ+dfCQk
    aefmj6j/DMFVSNkEQIpVHtk19tbxJCOhOoRSZhS1AoGACNq52u0OjUw+Ey1bLsXn
    bPLg9QhiAs925SoyGGT4zfnGoXWnYTyKbEV0hfJTQK6v1qOn7XWmE+wT2mT4AlCj
    mlsxaZTBAWoOsWSgIPhfRTyCwuEyuwwO8P2lan3YY4gFKU8r4z/+e1M/T11ph1oZ
    Xsux1IvnTvAGOyhF/9mA0aECgYBNIhnKTe2zSEtgzjdNSbU9hlIfZfhNVf+uQXZB
    +NcxLXccXu2xeA+WHfD2s8/P5Oy32ZpX7bJIOf0p8HKyIQsF3VejCt83tsDyVER4
    ZtDWOpldzpwFEvgK+xWvl0Q+a6BKWtGfkI3mn2dUJI4OQ4xJNM72Um6EWwVgzsjf
    I5GuZQKBgQC4oZbuRc96/qixGB0WOoIafWRzdR6VSCfrXxDgqjLVR9QI2F902Z2R
    28osRCHTP0Fzd/JPDmoM/KtEjIh0DXI4JK9sYEwJrec6nP/sfKTxsSDaEKY9n2qe
    6/Mu4i2D0q7JBy/4R1tvgR4joIy5ZlMvFcHzuFaCTw/noCRmxAr3hg==
    -----END RSA PRIVATE KEY-----
    
Frontend:
  hostname: localhost
  bind_address: 0.0.0.0
  bind_port: 8000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDdDCCAlygAwIBAgIRAL4ZwEql1TnFN+TgKvUybMwwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMDgyNjIxMjUxOVoXDTIz
    MDgyNjIxMjUxOVowNDEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRswGQYDVQQDExJW
    ZWxvY2lyYXB0b3JTZXJ2ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQCrjn7tr5P/HyPVlGgla2613SVwMCnTf7kk1s7aAVT9pY9AbDaChEc01pSXjggd
    DRe4FYDiuxV0LvfMOxaRdUhXyTWax4Kn2THcs8/98KEAgUzRCwUsLErEdQo+oBaf
    e7sSW5WgqpdpFQZ1p2EJS8cJMS1Er9FugfIuAbpRjO1yrMdbclCFYjTaynvOgy+X
    rBnj1QL5uG+QOdYRW4sfBrdPKVpi0TF3lvW9ip5UDaQ81nB3WoaChdtT0DwxEVU+
    tEV4PIbsFKFLa5cuS/mjVyPlcRdCtRpb5q2BRhRm0s7rF/iF4S9bC/xz8oPth1vA
    u+pvDd4uRcEKW2xfi1o17Uy9AgMBAAGjgZowgZcwDgYDVR0PAQH/BAQDAgWgMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1Ud
    IwQYMBaAFJLb+hleEb6A2oJEuv6Xnni26NwcMDcGA1UdEQQwMC6CElZlbG9jaXJh
    cHRvclNlcnZlcocECmQeBIYSVmVsb2NpcmFwdG9yU2VydmVyMA0GCSqGSIb3DQEB
    CwUAA4IBAQBway0VJipA7ZaccHX2nBTtIg72nlt5FqefQcthKLgI4Gg8WyGEzxaD
    s7Hvc2yQCMpwIbDvieuN2aPiVI5wLKYgknaNSPfM9yFkeFSHsZoSC2RqvQfGon81
    Nwbr0or3cvTIrirgikAd5/xadxx4utVcU0n+QxoLl1f1qGSEa/nQ4ro8iPN504Tx
    qhr8GR6ZYX+FwQdyxmeYZIceRh9PGkNjY8ejDTf3sJSQr30q/LvcuxVOCXUqmAO9
    hNEfM2MO8/cyvdzsgbiCre5DEW0cozIJKDy1/hPk6J+EzZ1vfS+2bMiMYwg3zU6h
    CYgKrloKYo3eZN/jmWy5CK8I9fOv9r9U
    -----END CERTIFICATE-----
    
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAq45+7a+T/x8j1ZRoJWtutd0lcDAp03+5JNbO2gFU/aWPQGw2
    goRHNNaUl44IHQ0XuBWA4rsVdC73zDsWkXVIV8k1mseCp9kx3LPP/fChAIFM0QsF
    LCxKxHUKPqAWn3u7EluVoKqXaRUGdadhCUvHCTEtRK/RboHyLgG6UYztcqzHW3JQ
    hWI02sp7zoMvl6wZ49UC+bhvkDnWEVuLHwa3TylaYtExd5b1vYqeVA2kPNZwd1qG
    goXbU9A8MRFVPrRFeDyG7BShS2uXLkv5o1cj5XEXQrUaW+atgUYUZtLO6xf4heEv
    Wwv8c/KD7YdbwLvqbw3eLkXBCltsX4taNe1MvQIDAQABAoIBAHHy4efp+Tk5a8nP
    GyXPp+dwDg/oTb/HVChd7WLsA5G+R9oYhlRGnC1CYcwQcN8q9Rg2YDc44FUdZUXn
    8WOILRbx9ILsBaKLJw1a+cnH7IizWVx4H2VpvfejbbyPBLfFrUnSPx5KcOtBJds7
    474S8Q7v9QtsZIUsFrnsN9825fiGJ6lupKuVaDjdZbCT6ar+966VoBIQDPWwetqd
    P3avfC+OvmcR84ekjUA9S4RFdOCegXsUxwx2tH9NjSbMWX5Y2qr5SNXdIHZ9SDcd
    k96f/K/lgPSja73MTmG8vdOfsxQ6Ey5xOD4rdZse3zkGq1uX36QzUOqPTLP/wpgg
    meubYQECgYEAxMPcOm2wFFiI2Smulx4RXShtEc3dfvJ3i13ZoJfvC0rPyQYq4+bi
    y+L2YC2DeIgTXNqFlh1QbENzUw7rArYU2T4pTBUzuQAmenTGUJaMLwCljQV7m5CN
    dMHj2n9IxTH+4gpIOXtOytSHNgcoOLWhCkJr7HX+IlJ/P5ecOtfNV2ECgYEA3zPj
    xhMGnVZc4nby/7px0zM6yK0zhno6rzl/54RbrLp0m+DUNOESs4L79ihqeiV+II2i
    PnnaPMUA5NOSGI3+9aSyrTrYEnyQ5wRdbbKdRuwxN65KXxyxuszAH/SQAko19461
    WZKC8B3ho8lhATngDvOOxwBADLJyYkx8HQabnt0CgYAhb+s/3p36hyUSSlwKACkR
    PKp0SRin1wprm5I9ETSlJZxz2+F0AyttXG9j3rglxnIL6HKlFOwyya+SYMmdF1Yp
    qL+Z10yH1rezPZ7p2PuPjTuU4GamBAWV3tEas2CpahqXTQoDAqpcG4uyqbqzEGKC
    fNEcSNzb9kr7gochFMUnYQKBgQCLIpiI/5EvAQfzr7x4hyuvQQ8Sy00ENitg0VIW
    6t4OxUgtZzBBKlBzEGKqJrWBIOAHwOJzWZgeK5wMCIrYvaNCUwGClNzeYUIekA0B
    dccuz8s6b24y7fsoe7wD73rZwpLzl8UaagcvUSE37S+ICSDPkSneiRxkDdTZy93O
    ZjEaDQKBgQCWlbUX0d1Sul8wX2uR39ZD8Xs76k2jB6BLSU7KTnLx3zXOaIVjHjAB
    SOJPMRIdTJROdAk+N2KCXYfTI+mk+qvHybrjT3JWvxNyAXZO8gbPoce3GNTcswh/
    T6U1smqrIsemFNO5DpLO7Xjlp+Dm5B1c2RX2xMhiPqic4YVpJgeC/g==
    -----END RSA PRIVATE KEY-----
    
  max_upload_size: 10485760
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  expected_clients: 10000
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
Datastore:
  implementation: FileBaseDataStore
  location: /var/tmp/velociraptor
  filestore_directory: /var/tmp/velociraptor
Writeback: {}
Mail: {}
Logging: {}
Monitoring:
  bind_address: 10.100.30.4
  bind_port: 8003
api_config: {}
obfuscation_nonce: icPEtWQRLWs=
